feature:
  config:
  - target: myconfigs/*
    link: $DESKMANAGE_TEST_DIR
  - target: myfile.txt
    link: $DESKMANAGE_TEST_DIR/mylinktofile.txt
  - target: mydir
    link: $DESKMANAGE_TEST_DIR/.mylinktodir
